-- 参加者が「領収書は必要か」に答えた結果を保存する（Issue #80）
--
-- LIFF の当日現金の申込画面で必ず聞くようにした。それより前に申し込んだ予約は
-- 答えを持たないので NULL のままにする。
--
-- ⚠️ **NULL を「不要」と解釈しないこと。**
--    DEFAULT 0 にすると、この列より前に入った予約が黙って領収書の対象外になり、
--    参加者に届かなくなっても誰も気づけない。既存行は NULL＝未回答のままにして、
--    発行処理は従来どおり（宛名 or 氏名で発行）続ける。
--    降りるのは receipt_requested = 0 のときだけ（services/freee-receipt.ts）。
--
--   1    = 領収書が必要（宛名は必須）
--   0    = 領収書は不要（freee を呼ばない）
--   NULL = 未回答（この機能より前の予約・API 直叩き）
ALTER TABLE event_bookings ADD COLUMN receipt_requested INTEGER;
